### ISSUE TITLE
Module works, but getting these error emails from REDCap

### ISSUE THREAD

**Issue by jasonlones** [lsgs/redcap-codebook-concertina#1]
[This message was automatically generated by REDCap]

The 'codebook_concertina' module threw the following exception when calling the hook method 'redcap_every_page_top':

Exception: You don't have permission to save project settings! You may want to use the disableUserBasedSettingPermissions() method to disable this check and leave permissions up the the module's code. in /var/www/html/redcap/redcap_v8.5.11/ExternalModules/classes/ExternalModules.php:864
Stack trace:
#0 /var/www/html/redcap/redcap_v8.5.11/ExternalModules/classes/ExternalModules.php(781): ExternalModules\ExternalModules::setSetting('codebook_concer...', 3371, 'button-text-sho...', 'Expand')
#1 /var/www/html/redcap/redcap_v8.5.11/ExternalModules/classes/AbstractExternalModule.php(222): ExternalModules\ExternalModules::setProjectSetting('codebook_concer...', 3371, 'button-text-sho...', 'Expand')
#2 /var/www/html/redcap/modules/codebook_concertina_v1.0.1/CodebookConcertina.php(133): ExternalModules\AbstractExternalModule->setProjectSetting('button-text-sho...', 'Expand')
#3 /var/www/html/redcap/modules/codebook_concertina_v1.0.1/CodebookConcertina.php(114): MCRI\CodebookConcertina\CodebookConcertina->getButtonText('button-text-sho...', 'Expand')
#4 /var/www/html/redcap/modules/codebook_concertina_v1.0.1/CodebookConcertina.php(26): MCRI\CodebookConcertina\CodebookConcertina->getShowButtonText()
#5 [internal function]: MCRI\CodebookConcertina\CodebookConcertina->redcap_every_page_top('3371')
#6 /var/www/html/redcap/redcap_v8.5.11/ExternalModules/classes/ExternalModules.php(1320): call_user_func_array(Array, Array)
#7 /var/www/html/redcap/redcap_v8.5.11/ExternalModules/classes/ExternalModules.php(1405): ExternalModules\ExternalModules::startHook('codebook_concer...', 'v1.0.1', Array)
#8 /var/www/html/redcap/redcap_v8.5.11/Classes/Hooks.php(37): ExternalModules\ExternalModules::callHook('every_page_top', Array)
#9 /var/www/html/redcap/redcap_v8.5.11/Views/HeaderProject.php(39): Hooks::call('redcap_every_pa...', Array)
#10 /var/www/html/redcap/redcap_v8.5.11/ProjectGeneral/header.php(6): require('/var/www/html/r...')
#11 /var/www/html/redcap/redcap_v8.5.11/Design/data_dictionary_codebook.php(6): require_once('/var/www/html/r...')
#12 {main}

**Comment by lsgs** [comment]
Thanks @jasonlones.  I checked and I just stuffed up release 1.0.1 - it did not contain the fix for this problem that I thought it did! Release 1.0.2 does, and I have submitted it to the REDCap repo.

**Comment by jasonlones** [comment]
@lsgs, thank you, sir!
