### ISSUE TITLE
wrong "View on GitHub" link?

### ISSUE THREAD

**Issue by wibeasley** [lsgs/redcap-codebook-concertina#2]
@lsgs, I was checking out this module's entry on the [REDCap repo](https://redcap.vanderbilt.edu/consortium/modules/index.php).  The link for "View on GitHub" directs to `https://github.com/lsgs/redcap-codebook-concertina/archive/1.0.2.zip`.

Should this be changed to `https://github.com/lsgs/redcap-codebook-concertina`?

**Comment by lsgs** [comment]
Yes, @wibeasley, you're right. I probably pasted it wrong in the module submission survey. I'll do another submission...
Thanks!
